version: '2'
services:
  zookeeper:
    restart: always
    image: confluentinc/cp-zookeeper:5.3.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    restart: always
    image: confluentinc/cp-kafka:5.3.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9091:9091"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_BOOTSTRAP.SERVERS: 'broker:29091'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29091,PLAINTEXT_HOST://127.0.0.1:9091
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    depends_on:
      - broker
    ports:
      - "6379:6379"
  database:
    restart: always
    image: "mariadb:10.5.3"
    depends_on:
      - redis
    ports:
      - "3306:3306"
    volumes:
      - ./db:/tmp/db
      - ./db/data:/var/lib/mysql:rw
      - ./db/initdb.d/install_db.sql:/docker-entrypoint-initdb.d/install_db.sql:ro # init table
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: "exchange_portal"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "12345678"
  exchange-portal:
    restart: always
    image: exchange-portal
    hostname: exchange-portal
    container_name: exchange-portal
    ports:
      - "8083:8083"
    depends_on:
      - database
    environment:
      env_name: dev
      kafka_console_ip: broker:9091
      spring_datasource_primary_ip: database:3306
      spring_datasource_primary_password: 12345678
      spring_datasource_primary_username: admin
      spring_kafka_bootstrap_ip: broker
      spring_kafka_bootstrap_port: 9091
      spring_redis_host: redis
      spring_redis_port: 6379
      addition_env_name: exchange
      server_port: 8083
