# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1
jobs:
  test:
    docker:
      - image: cimg/openjdk:8.0.392
    working_directory: ~/exchange-portal
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Run tests
          command: mvn test
  build:
    docker:
      - image: cimg/openjdk:8.0.392
    steps:
      - checkout
      # Replace this with steps to build a package, or executable
      - run:
          name: Build an artifact
          command: mvn clean install -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          key: exchange-portal-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: target/classes
          destination: exchange-portal
  # deploy:
  #   docker:
  #     - image: cimg/base:stable
  #   steps:
  #     # Replace this with steps to deploy to users
  #     - run:
  #         name: deploy
  #         command: "#e.g. ./deploy.sh"
workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test